### ISSUE TITLE
Need appsettings.json example

### ISSUE THREAD

**Issue by ixm7** [mantasaudickas/serilog-sinks-logz-io#10]
Please add appsettings.json configuration example to the Read.Me

**Comment by frankaxela** [comment]
Can be found here:
https://github.com/mantasaudickas/serilog-sinks-logz-io/blob/master/tests/Serilog.Sinks.Logz.Io.AspNetCoreApi/appsettings.json

**Comment by mantasaudickas** [comment]
Sorry, really had no time for this..
But maybe this also helps:
https://github.com/tsimbalar/serilog-settings-comparison/blob/master/docs/README.md

**Comment by mantasaudickas** [comment]
I am closing issue since some examples were already provided.
