### ISSUE TITLE
Connect to EU server and use of different port

### ISSUE THREAD

**Issue by tszaniszlo** [mantasaudickas/serilog-sinks-logz-io#13]
Logz.io provided me a URL with port 443 where I can send in bulk HTTPS requests. In the app it is not possible to configure the url/Port. I would like to have that configurable too.

**Comment by mantasaudickas** [comment]
Added a possibility to specify port in version 2.3.0

**Comment by tszaniszlo** [comment]
Thanks for this fix for the port, how bout the server URL? that is not the standard eu server I have
