### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by scott-david-walker** [mantasaudickas/serilog-sinks-logz-io#17]
Is it possible to consider adding durable file based logging?

**Comment by mantasaudickas** [comment]
Dreaming about this since first commit, but had no time so far... :)

**Comment by scott-david-walker** [comment]
If you ever want a hand then I'd like to collaborate to help you get this going! :-)

**Comment by mantasaudickas** [comment]
Sorry for a long delay. 
Please take a look here: https://github.com/mantasaudickas/serilog-sinks-logz-io/tree/master/src/Serilog.Sinks.Http.LogzIo
Its based on Serilog.Sinks.Http package.
