### ISSUE TITLE
Not working in Production/AWS EKS

### ISSUE THREAD

**Issue by nambir** [mantasaudickas/serilog-sinks-logz-io#18]
Hi Team,
I am able to ship logs to logzio from my local system. When i deploy the same code to AWS EKS, the logs are not shipping to logzio, any idea?

**Comment by mantasaudickas** [comment]
Have you checked if machine has access to internet?
Does it have access to logz.io data center?
Does it have access to logz.io data center ports?

**Comment by mantas-amberlo** [comment]
Closing this as not enough information.

**Comment by mantasaudickas** [comment]
Closing as not enough information.
