### ISSUE TITLE
Logz.io has different endpoints for datacentres

### ISSUE THREAD

**Issue by bonejon** [mantasaudickas/serilog-sinks-logz-io#7]
Hi,

We are using the EU datacentre which has a different endpoint to the US. I have added the functionality to specify the configuration in PR #6 which takes the subdomain as a parameter, this should be extensible if they choose to add more sub-domains.

The default sub-domain should always be listener to allow for easy backward compatability.

**Comment by mantasaudickas** [comment]
Thank you for pull request.
I have published changes with package version 2.1.2:
https://www.nuget.org/packages/Serilog.Sinks.Logz.Io/2.1.2
